apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-hosts
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: vittinho46.com.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vittinho46
                port: 8081
