name: Backstage ms deploy

env:
  PROJETO: "backstage-coe"
  EMAIL: "walber.silva@sysmap.com.br"
  NAMESPACE: "backstage"
on:
  push:
    branches:
      - "main"

jobs:
  kaniko:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: vittormaciel/vittinho46:latest
  deploy:
    runs-on: self-hosted
    needs: "kaniko"
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://vault.mycompany.com:8200
          token: ${{ secrets.VAULT_TOKEN }}
          caCertificate: ${{ secrets.VAULT_CA_CERT }}
          secrets: |
            coe-secrets/backstage kubeconfig | KUBECONFIG
      - name: Set short git commit SHA
        id: vars
        run: |
          sed -i 's,$REGISTRY.*,walber7/node-web-app,' k8s/helm/values.yaml
          sed -i 's,tag:.*",tag: \"${{ '${{ github.run_number }}' }}\",' k8s/helm/values.yaml
          echo "${{ '${{ steps.import-secrets.outputs.KUBECONFIG }}' }}" | base64 -d > kubeconfig.backstage
      - name: Helm tool installer
        uses: Azure/setup-helm@v3
      - name: Deploy
        run: |
          helm upgrade --install backstage-teste k8s/helm/ -n backstage-ms
        env:
          KUBECONFIG: kubeconfig.backstage
