    # build-image:
    #   runs-on: vittor-github
    #   needs: build
    #   steps:
    #     - uses: actions/checkout@v3
    #     - uses: actions/download-artifact@master
    #       with:
    #         name: jar-file
    #         path: app.jar
    #     - name: Set up QEMU
    #       uses: docker/setup-qemu-action@v2
    #     - name: Set up Docker Buildx
    #       uses: docker/setup-buildx-action@v2
    #     - name: Login to Docker Hub
    #       uses: docker/login-action@v2
    #       with:
    #         username: ${{ secrets.DOCKERHUB_USERNAME }}
    #         password: ${{ secrets.DOCKERHUB_TOKEN }}
    #     - name: Build and push
    #       uses: docker/build-push-action@v3
    #       with:
    #         context: .
    #         push: true
    #         tags: vittormaciel/helloworld-java:latest
        
    # deploy:
    #   runs-on: vittor-github
    #   needs: build-image
    #   steps:
    #     - uses: actions/checkout@v3
    #     - uses: azure/k8s-set-context@v3
    #       with:
    #         method: kubeconfig
    #         kubeconfig: ${{ secrets.MYMINIKUBE_KUBECONFIG }}
    #     - name: kubectl-simple
    #       uses: steebchen/kubectl@v2.1.1
    #       with:
    #         config: ${{ secrets.MYMINIKUBE_KUBECONFIG }}
    #         command: apply -f deployment.yaml
